### ISSUE TITLE
build error on Ubuntu 16.04: 

### ISSUE THREAD

**Issue by oleid** [FlexCoreLib/flexcore#1]
Dear flexcore developers,

I just noticed a build error on Ubuntu 16.04:

<pre>
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/clock.cpp:8:
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/clock.hpp:11:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/atomic:185:7: error: exception specification of explicitly defaulted default constructor does not match the calculated one
      atomic() noexcept = default;
      ^
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/clock.cpp:16:26: note: in instantiation of template class 'std::atomic<std::chrono::time_point<fc::virtual_clock::system,
      std::chrono::duration<long, std::ratio<1, 1000000000> > > >' requested here
                virtual_clock::system::current_time((
                                       ^
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/clock.cpp:8:
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/clock.hpp:11:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/atomic:185:7: error: exception specification of explicitly defaulted default constructor does not match the calculated one
      atomic() noexcept = default;
      ^
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/clock.cpp:20:26: note: in instantiation of template class 'std::atomic<std::chrono::time_point<fc::virtual_clock::steady,
      std::chrono::duration<long, std::ratio<1, 1000000000> > > >' requested here
                virtual_clock::steady::current_time((
                                       ^
2 errors generated.
</pre>

This is with clang-3.8, but using Ubuntu's gcc-5.4 yields a related problem:

<pre>
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp: In instantiation of ‘fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)> [with auto:1 = fc::thread::periodic_task]’:
/usr/include/c++/5/type_traits:2346:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__success_type<decltype (declval<_Fn>()((declval<_Args>)()...))> std::__result_of_other_impl::_S_test(int) [with _Fn = fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>; _Args = {fc::thread::periodic_task&}]’
/usr/include/c++/5/type_traits:2357:55:   required from ‘struct std::__result_of_impl<false, false, fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>, fc::thread::periodic_task&>’
/usr/include/c++/5/type_traits:2361:12:   required from ‘class std::result_of<fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>(fc::thread::periodic_task&)>’
/usr/include/c++/5/functional:2053:9:   required by substitution of ‘template<class _Functor, class, class> std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>; <template-parameter-1-2> = void; <template-parameter-1-3> = <missing>]’
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/cyclecontrol.hpp:179:70:   required from ‘fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>, ErrorFun) [with ErrorFun = fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>]’
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp:21:22:   required from here
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp:21:21: error: cannot call member function ‘bool fc::thread::cycle_control::store_exception(fc::thread::periodic_task&)’ without object
                     })
                     ^
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp:1:0:
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/cyclecontrol.hpp: In instantiation of ‘fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>, ErrorFun) [with ErrorFun = fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>]’:
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp:21:22:   required from here
/home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/cyclecontrol.hpp:179:70: error: no matching function for call to ‘std::function<bool(fc::thread::periodic_task&)>::function(std::remove_reference<fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>&>::type)’
     : scheduler_(std::move(scheduler)), error_callback(std::move(err))
                                                                      ^
In file included from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/scheduler.hpp:4:0,
                 from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/../flexcore/scheduler/cyclecontrol.hpp:5,
                 from /home/oleid/sync/prog/opencl/flexcore_cl/3rdparty/flexcore/flexcore/scheduler/cyclecontrol.cpp:1:
/usr/include/c++/5/functional:2054:2: note: candidate: template<class _Functor, class, class> std::function<_Res(_ArgTypes ...)>::function(_Functor)
  function(_Functor);
  ^
/usr/include/c++/5/functional:2054:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/functional:2028:7: note: candidate: std::function<_Res(_ArgTypes ...)>::function(std::function<_Res(_ArgTypes ...)>&&) [with _Res = bool; _ArgTypes = {fc::thread::periodic_task&}]
       function(function&& __x) : _Function_base()
       ^
/usr/include/c++/5/functional:2028:7: note:   no known conversion for argument 1 from ‘std::remove_reference<fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>&>::type {aka fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>}’ to ‘std::function<bool(fc::thread::periodic_task&)>&&’
/usr/include/c++/5/functional:2232:5: note: candidate: std::function<_Res(_ArgTypes ...)>::function(const std::function<_Res(_ArgTypes ...)>&) [with _Res = bool; _ArgTypes = {fc::thread::periodic_task&}]
     function<_Res(_ArgTypes...)>::
     ^
/usr/include/c++/5/functional:2232:5: note:   no known conversion for argument 1 from ‘std::remove_reference<fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>&>::type {aka fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>}’ to ‘const std::function<bool(fc::thread::periodic_task&)>&’
/usr/include/c++/5/functional:2008:7: note: candidate: std::function<_Res(_ArgTypes ...)>::function(std::nullptr_t) [with _Res = bool; _ArgTypes = {fc::thread::periodic_task&}; std::nullptr_t = std::nullptr_t]
       function(nullptr_t) noexcept
       ^
/usr/include/c++/5/functional:2008:7: note:   no known conversion for argument 1 from ‘std::remove_reference<fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>&>::type {aka fc::thread::cycle_control::cycle_control(std::unique_ptr<fc::thread::scheduler>)::<lambda(auto:1&)>}’ to ‘std::nullptr_t’
/usr/include/c++/5/functional:2001:7: note: candidate: std::function<_Res(_ArgTypes ...)>::function() [with _Res = bool; _ArgTypes = {fc::thread::periodic_task&}]
       function() noexcept
       ^
/usr/include/c++/5/functional:2001:7: note:   candidate expects 0 arguments, 1 provided
</pre>

Can you reproduce it at your end?

**Comment by jepio** [comment]
These are known issues. The second one is (I believe) gcc bug [67274](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274), to fix it cyclecontrol.cpp:21 should be changed to `this->store_exception(...)`. The first one is fixed by building against libc++ (`-stdlib=libc++`) when compiling with clang.

**Comment by CasparKielwein** [comment]
We are currently preparing to push changes from a company internal repository to upstream.
These should fix the gcc issue as they include major improvements of the cyclecontrol code.
